import type { SpecialistCard } from "@/types"
import type { CategoryOption } from "@/components/explore/explore-filters-toolbar"

export const MOCK_CATEGORIES: CategoryOption[] = [
  { slug: "medicina-general", name: "Medicina General", icon: "⚕️", professionalCount: 12 },
  { slug: "bienestar", name: "Bienestar", icon: "🧘", professionalCount: 8 },
  { slug: "especialidades", name: "Especialidades", icon: "🔬", professionalCount: 24 },
]

export const MOCK_SPECIALTY_OPTIONS = [
  { value: "", label: "Seleccionar especialidad..." },
  { value: "medicina-general", label: "Medicina General" },
  { value: "psicologia", label: "Psicología" },
  { value: "nutricion", label: "Nutrición" },
  { value: "kinesiologia", label: "Kinesiología" },
  { value: "pediatria", label: "Pediatría" },
]

export const MOCK_SPECIALISTS: SpecialistCard[] = [
  {
    id: "1",
    slug: "especialista-test",
    name: "Dra. María González",
    specialty: "Medicina General",
    specialtySlug: "medicina-general",
    category: "Medicina",
    categorySlug: "medicina-general",
    avatarUrl: null,
    rating: 5.0,
    reviewCount: 10,
    price: 30000,
    onlinePrice: 28000,
    inPersonPrice: 32000,
    consultationType: "both",
    location: "Santiago, Chile",
    verified: true,
    yearsExperience: 10,
    languages: ["Español"],
    bio: "Médico general con amplia experiencia en atención primaria y medicina preventiva.",
    university: "Universidad de Chile",
    isAvailableToday: true,
  },
  {
    id: "2",
    slug: "dr-pablo-lagos",
    name: "Dr. Pablo Lagos",
    specialty: "Psicología Clínica",
    specialtySlug: "psicologia",
    category: "Bienestar",
    categorySlug: "bienestar",
    avatarUrl: null,
    rating: 4.8,
    reviewCount: 24,
    price: 35000,
    onlinePrice: 35000,
    inPersonPrice: 40000,
    consultationType: "online",
    location: null,
    verified: true,
    yearsExperience: 8,
    languages: ["Español", "Inglés"],
    bio: "Terapia cognitivo-conductual y apoyo en ansiedad y estrés.",
    university: "Pontificia Universidad Católica",
    isAvailableToday: false,
  },
  {
    id: "3",
    slug: "especialista-sin-resenas",
    name: "Especialista Test",
    specialty: "Medicina General",
    specialtySlug: "medicina-general",
    category: "Medicina",
    categorySlug: "medicina-general",
    avatarUrl: null,
    rating: 0,
    reviewCount: 0,
    price: 30000,
    onlinePrice: 30000,
    inPersonPrice: 30000,
    consultationType: "both",
    location: "Viña del Mar",
    verified: false,
    yearsExperience: 2,
    languages: ["Español"],
    bio: "Médico general con amplia experiencia en atención primaria.",
    university: null,
    isAvailableToday: false,
  },
]
